Algoritmo "quest03"
//  
//  
// 
//
//
//
// Função: Mostra na tela o nome e o salário do funcionário
// Autor(a): Juliana Rodrigues Ferreira
// Ano: 2024
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara

Var
n: caractere
s: real


Inicio
escreva("Digite seu nome: ")
leia (n)
escreva ("Salario: ")
leia (s)
escreval ("O funcionário(a)", n , "tem o salário de", s)




Fimalgoritmo