Algoritmo "Quest06"
//  
//  
//função: ler um número inteiro e mostrar seu antecessor e seu sucessor
//Autor(a): Juliana Rodrigues Ferreira
//Ano: 2025
// Lista de Exercícios do Curso em Video- Prof: Gustavo Guanabara


Var
   N,A,S: Inteiro


Inicio
   escreva("Informe um número: ")
   leia (N)
   A <- N -1
   S <- N + 1
   escreval("O Antecessor de ", N, " é igual a ", A)
   escreva ("O sucesssor de ", N, " é igual a ", S)


Fimalgoritmo